name = "keys"
main = "dist/index.mjs"
compatibility_date = "2022-12-14"
send_metrics = false
kv_namespaces = [
    { binding = "KV_KEYS", id = "457a885a763f484885d5f87c9a95a519" }
]
route = "keys.mealuet.com/*"

[vars]
USER = "kressety"
