on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js environment
      uses: actions/setup-node@v4.0.1
      with:
        node-version: 21

    - name: Install Deps
      run: yarn install

    - name: Build
      run: yarn build
    
    - name: 'Deploy to Cloudflare Workers with Wrangler'
      uses: cloudflare/wrangler-action@v3.1.0
      with:
        apiToken: ${{ secrets.CF_API_TOKEN }}
        accountId: ${{ secrets.CF_ACCOUNT_ID }}
